services:
  db:
    image: postgres # Use the official Postgres image
    environment:
      POSTGRES_USER: ghost # Set your DB user
      POSTGRES_PASSWORD: "Andy51916" # Set your DB password
      POSTGRES_DB: thestoneking # Set your DB name
    ports:
      - "5433:5432" # Expose port 5432 to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist DB data across restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ghost -d thestoneking"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  app:
    image: dgarcia51/thestoneking:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://ghost:Andy51916@thestoneking_db:5432/thestoneking" # DB connection URL
      USERNAME: "berna306"
      PASSWORD: "Ezra123006"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      order: start-first
    depends_on:
      - db
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network:
    driver: overlay
